---
- name: Install apache2
  apt:
    name: apache2
    state: present

- name: enabling mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: enabling mod_ssl
  apache2_module:
    name: ssl
    state: present

- name: Create host config
  template: 
    src: templates/vhost.conf
    dest: "/etc/apache2/sites-available/{{ ansible_env.VIRTUAL_HOST }}.conf"

- name: "a2ensite {{ ansible_env.VIRTUAL_HOST }}"
  command: "a2ensite {{ ansible_env.VIRTUAL_HOST }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ ansible_env.VIRTUAL_HOST }}.conf"

- name: "a2dissite 000-default.conf"
  command: "a2dissite 000-default.conf"

- name: set servername
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: ServerName localhost

# create and assign self-signed SSL certificate

- name: generate self-signed certificate for ssl
  command: openssl req -new -nodes -x509 -subj "/C=DE/ST=Berlin/L=Berlin/O=IT/CN={{ ansible_env.VIRTUAL_HOST }}" -days 3650 -keyout /etc/apache2/ssl/{{ ansible_env.VIRTUAL_HOST }}.key -out /etc/apache2/ssl/{{ ansible_env.VIRTUAL_HOST }}.crt -extensions v3_ca creates=/etc/apache2/ssl/{{ ansible_env.VIRTUAL_HOST }}.crt
